import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/layout/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 dark:bg-gray-900">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
